version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: talentus.com/laravel:3.1
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    networks:
      - talentus-network
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - talentus-network
  #MySQL Service
  db:
    image: mysql:8.0.30
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3406:3306"
    environment:
      MYSQL_DATABASE: talentus
      MYSQL_ROOT_PASSWORD: talentus
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - talentus-network
#Docker Networks
networks:
  talentus-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local